name: Auto Blog Generation
on:
  schedule:
    # Run 3 times per week: Monday, Wednesday, Friday at 6 PM UTC
    - cron: '0 18 * * 1'  # Monday
    - cron: '0 18 * * 3'  # Wednesday  
    - cron: '0 18 * * 5'  # Friday
  workflow_dispatch:  # Allow manual trigger

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
  REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow
          
      - name: Generate blog with AI image
        id: generate
        run: |
          cd scripts/
          python automated_blog_system.py
          
      - name: Check if blog was generated
        id: check
        run: |
          if [ -f "../blog_generation_result.json" ]; then
            echo "BLOG_GENERATED=true" >> $GITHUB_OUTPUT
            echo "Blog was generated successfully"
          else
            echo "BLOG_GENERATED=false" >> $GITHUB_OUTPUT
            echo "No blog scheduled for today"
          fi
          
      - name: Commit and push if blog generated
        if: steps.check.outputs.BLOG_GENERATED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes
          git add .
          
          # Commit with descriptive message
          if [ -f "blog_generation_result.json" ]; then
            RESULT=$(cat blog_generation_result.json)
            TITLE=$(echo $RESULT | jq -r '.title')
            TYPE=$(echo $RESULT | jq -r '.type')
            echo "🤖 Auto-generated $TYPE blog: $TITLE"
            git commit -m "🤖 Auto-generated $TYPE blog: $TITLE"
          else
            git commit -m "🤖 Auto-generated blog post"
          fi
          
          # Push to main branch
          git push origin main
          
      - name: Create summary
        if: steps.check.outputs.BLOG_GENERATED == 'true'
        run: |
          if [ -f "blog_generation_result.json" ]; then
            echo "## 🎉 Blog Generated Successfully!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📝 Blog Details:" >> $GITHUB_STEP_SUMMARY
            RESULT=$(cat blog_generation_result.json)
            echo "- **Title:** $(echo $RESULT | jq -r '.title')" >> $GITHUB_STEP_SUMMARY
            echo "- **Type:** $(echo $RESULT | jq -r '.type')" >> $GITHUB_STEP_SUMMARY
            echo "- **File:** $(echo $RESULT | jq -r '.filename')" >> $GITHUB_STEP_SUMMARY
            echo "- **Image:** $(echo $RESULT | jq -r '.image')" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🚀 Your blog is now live and SEO-ready!" >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: No blog scheduled
        if: steps.check.outputs.BLOG_GENERATED == 'false'
        run: |
          echo "## ⏰ No Blog Scheduled Today" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📅 **Schedule:**" >> $GITHUB_STEP_SUMMARY
          echo "- **Monday:** Advanced blog with code examples" >> $GITHUB_STEP_SUMMARY
          echo "- **Wednesday:** SEO-optimized blog" >> $GITHUB_STEP_SUMMARY
          echo "- **Friday:** Simple daily blog" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Next scheduled blog will be generated automatically!" >> $GITHUB_STEP_SUMMARY
