name: Auto Tech Blog
on:
  schedule:
    - cron: '0 18 * * 3' # Every Wednesday at 6PM UTC
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Test scripts
        run: |
          python scripts/trends.py
          python scripts/writer.py
          python scripts/rewriter.py
          python scripts/seo.py
