name: Auto Tech Blog (Debug)
on:
  workflow_dispatch:  # Disable schedule temporarily
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show directory structure
        run: |
          echo "=== Repository Contents ==="
          ls -R
          echo "=== Scripts Folder ==="
          ls -l scripts/
          
      - name: Test Python installation
        run: |
          echo "Python version:"
          python --version
          echo "Pip list:"
          pip list
